defaults: &defaults
  host: '127.0.0.1'
  identity_map_enabled: true
  
development:
  <<: *defaults
  database: chatpro_dev

test:
  <<: *defaults
  database: chatpro_test

# set these environment variables on your prod server
production:
  database: chatpro
  host: '127.0.0.1'
  
# development:
  # host: localhost
  # database: chatpro_development
# 
# test:
  # host: localhost
  # database: chatpro_test
# 
# # set these environment variables on your prod server
# production:
  # host: <%= ENV['MONGOID_HOST'] %>
  # port: <%= ENV['MONGOID_PORT'] %>
  # username: <%= ENV['MONGOID_USERNAME'] %>
  # password: <%= ENV['MONGOID_PASSWORD'] %>
  # database: <%= ENV['MONGOID_DATABASE'] %>
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019
